name: SnapLogic CI/CD

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install unzip
      run: sudo apt-get install unzip

    - name: Extract SnapLogic project export
      run: |
        mkdir export
        unzip snaplogic/Mulecraft_Demo-mga-dev.zip -d export

    - name: Deploy to SnapLogic
      run: |
        curl -u "${{ secrets.SNAP_USERNAME }}:${{ secrets.SNAP_PASSWORD }}" \
        -X POST \
        -H "Content-Type: application/json" \
        -d @export/project.json \
        "${{ secrets.SNAP_BASE_URL }}/api/1/rest/public/runtime/project/${{ secrets.SNAP_PROJECT }}"
